### PR TITLE
Update to 2.0.1 and add support for osx_arm64

### PR DESCRIPTION
**Pull request by ccordoba12**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #13

### CODE REVIEW

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
@conda-forge/wurlitzer, @conda-forge/core, could you merge this one? It's the last dependency of `spyder-kernels` without support for `osx_arm64`.

I also took the liberty to add myself as a maintainer, given that this package is important for Spyder.

**Comment by beckermr** [comment]
We generally wait about a week for these requests.

**Comment by beckermr** [comment]
If the recipe maintainers have not merged it by then, bump us again.

**Comment by ccordoba12** [comment]
Hey @beckerm, thanks for the quick response. No problem, I'll wait then.

**Pull request merged**
